Update documentation
MoravianUniversity/mirrulations pull request #164
Opened 2023-04-21 16:18 UTC by tylervalentine

What we have so far:
- Removed mongo collection and work server doc files
- Updated production doc file descriptions of various packages throughout the project
- Removed mention of work server in the client doc file

What still needs to be done:
- Remove (or update?) EC2-Mongo doc file
- Mention attachments in API doc file
- Remove endpoints relating to the work server in client doc file, and possibly document any important functions

2023-04-21 18:28 UTC, tylervalentine commented
This PR is ready for review.

2023-04-21 19:11 UTC, justinszaro requested changes

2023-04-21 19:11 UTC, justinszaro commented on docs/api.md
> +Additionally, if a document/comment is being retrieved, it will return any attachments that go along with that document/comment. These can be identified in the JSON given under data/attributes/fileFo
You may want to include that the client will also turn around and download these attachments.

2023-04-21 19:11 UTC, justinszaro commented on docs/client.md
> +The clients are their own objects that will request work from the job queue, perform the work by making calls to [regulations.gov]
"and perform the work by making calls..."

2023-04-21 19:11 UTC, justinszaro commented on docs/production.md
>  * `docker compose down` to bring the system down
Could you add the --tail=## tag to the documentation as well? It may be helpful for the next class to know.

2023-04-21 19:33 UTC, justinszaro requested changes

2023-04-21 19:33 UTC, justinszaro commented on docs/production.md
> +	* `--tail <number>` add to display a specific number of logs
The tag is --tail=<number>

2023-04-24 14:37 UTC, justinszaro approved these changes

2023-04-24 14:37 UTC, merged